name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: yarn

    - name: Run build
      run: yarn build

    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with: # Agora vamos utilizar os secrets
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: ".,!node_modules"
        target: "~/apps/barbershop/ts-barbershop-backend/"

    - name: Install dependencies on Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/apps/barbershop/ts-barbershop-backend/
          yarn

    - name: Run migrations on Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/apps/barbershop/ts-barbershop-backend/
          ./node_modules/.bin/typeorm migration:run

    - name: Restart Node server on Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: pm2 restart barbershop-api
